DROP TABLE IF EXISTS "ums_data";

CREATE TABLE "ums_data"(
"id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
"dc" INT4 DEFAULT NULL ,
PRIMARY KEY ("id") 
);
COMMENT ON TABLE "ums_data" IS '数据迁移表';
COMMENT ON COLUMN "ums_data"."id" IS '数据迁移ID';
COMMENT ON COLUMN "ums_data"."dc" IS '数据迁移标识';

